sudo: required
services:
  - docker

before_install: 
  - docker build -t azajvahora/fibonacci-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run azajvahora/fibonacci-test npm test -- --coverage

after_success: 
  - docker build -t azajvahora/fibonacci-client ./client
  - docker build -t azajvahora/fibonacci-nginx ./nginx
  - docker build -t azajvahora/fibonacci-server ./server
  - docker build -t azajvahora/fibonacci-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images to Docker Hub
  - docker push azajvahora/fibonacci-client
  - docker push azajvahora/fibonacci-nginx
  - docker push azajvahora/fibonacci-server
  - docker push azajvahora/fibonacci-worker